### ISSUE TITLE
Testing for non-functional features

### ISSUE THREAD

**Issue by dseben** [BME-MIT-IET/iet-hf2021-meg-iet#17]
The main objective for these tests is as follows: 

- performance
- security
- stress test
- usability

**Comment by dseben** [comment]
The pull request and commits for the stress test:
**#11 Stress test**

[Upload files for stress test](https://github.com/BME-MIT-IET/iet-hf2021-meg-iet/pull/15/commits/695772d55a03a387d904f90fa47723896388d8f1)
[Add documentation for stress test](https://github.com/BME-MIT-IET/iet-hf2021-meg-iet/pull/15/commits/48e33616877b85f56609c38caa1f4b5686c55fd0)
[Extend documentation](https://github.com/BME-MIT-IET/iet-hf2021-meg-iet/pull/15/commits/042c3368e038a9f7acdf6d6990eb07628e10ec3c)

**Comment by eperst** [comment]
The pull request and commits for the performance test:
#14 **Performance test**
**Relevant commits:**
[feat: add basic runtime logging](https://github.com/BME-MIT-IET/iet-hf2021-meg-iet/pull/14/commits/11ad8571eb56f00dbb4e550243fe6a1c37ad23d8)
[chore: performance test wind turbine data](https://github.com/BME-MIT-IET/iet-hf2021-meg-iet/pull/14/commits/58299153a0fac2a045598885b2523796b67f2d82)
[feat: basic documentation of wind conversion](https://github.com/BME-MIT-IET/iet-hf2021-meg-iet/pull/14/commits/bef0689c67f163907b1b5e48263ed5231d1d457a)
[chore: rename stress-test to performance-tests](https://github.com/BME-MIT-IET/iet-hf2021-meg-iet/pull/14/commits/af68aa9970f7fe7bc58125f150f7e604cca63fd8)
[chore: update performance-tests.md](https://github.com/BME-MIT-IET/iet-hf2021-meg-iet/pull/14/commits/0e86837b44b362e97114c968942412451dad889c)

**Comment by Lacieee** [comment]
**#10 Usability and security test**

Documentation and testing
